// Kommit helper library — single source of truth for PDA derivation,
// program client construction, and Supabase client construction.
//
// Frontend code (server + client components) and the indexer
// (app/web/src/app/api/webhook/helius/route.ts) both import from here.
// Don't duplicate PDA derivation in two places.
//
// Path note: imports `../../../target/types/kommit` which is generated by
// `anchor build` at the workspace root. Run anchor build before tsc'ing
// the web app for the first time, or after pulling new program code.

import * as anchor from "@coral-xyz/anchor";
import { PublicKey } from "@solana/web3.js";
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import idl from "./idl/kommit.json";
import type { Kommit } from "./idl/kommit";

export type { Kommit };

// ---------------------------------------------------------------------------
// Program ID + seeds — keep aligned with programs/kommit/src/state.rs.
// ---------------------------------------------------------------------------

export const KOMMIT_PROGRAM_ID = new PublicKey(
  process.env.NEXT_PUBLIC_KOMMIT_PROGRAM_ID ??
    "GxM3sxMp4FyrkHK4g1DaDrmwYLrwd2BJKxqKZqvGgkc3"
);

export const SEEDS = {
  config: Buffer.from("config"),
  project: Buffer.from("project"),
  commitment: Buffer.from("commitment"),
  escrow: Buffer.from("escrow"),
  collateral: Buffer.from("collateral"),
  lending: Buffer.from("lending"),
} as const;

export const ADAPTER = {
  Kamino: 0,
} as const;
export type AdapterId = (typeof ADAPTER)[keyof typeof ADAPTER];

// ---------------------------------------------------------------------------
// PDA derivation. Pure — doesn't need a connection.
// ---------------------------------------------------------------------------

export function findConfigPda(programId: PublicKey = KOMMIT_PROGRAM_ID): PublicKey {
  return PublicKey.findProgramAddressSync([SEEDS.config], programId)[0];
}

export function findProjectPda(
  recipientWallet: PublicKey,
  programId: PublicKey = KOMMIT_PROGRAM_ID
): PublicKey {
  return PublicKey.findProgramAddressSync(
    [SEEDS.project, recipientWallet.toBuffer()],
    programId
  )[0];
}

export function findCommitmentPda(
  user: PublicKey,
  project: PublicKey,
  programId: PublicKey = KOMMIT_PROGRAM_ID
): PublicKey {
  return PublicKey.findProgramAddressSync(
    [SEEDS.commitment, user.toBuffer(), project.toBuffer()],
    programId
  )[0];
}

export function findEscrowPda(
  project: PublicKey,
  programId: PublicKey = KOMMIT_PROGRAM_ID
): PublicKey {
  return PublicKey.findProgramAddressSync(
    [SEEDS.escrow, project.toBuffer()],
    programId
  )[0];
}

export function findCollateralPda(
  project: PublicKey,
  programId: PublicKey = KOMMIT_PROGRAM_ID
): PublicKey {
  return PublicKey.findProgramAddressSync(
    [SEEDS.collateral, project.toBuffer()],
    programId
  )[0];
}

export function findLendingPositionPda(
  project: PublicKey,
  adapter: AdapterId = ADAPTER.Kamino,
  programId: PublicKey = KOMMIT_PROGRAM_ID
): PublicKey {
  return PublicKey.findProgramAddressSync(
    [SEEDS.lending, project.toBuffer(), Buffer.from([adapter])],
    programId
  )[0];
}

// ---------------------------------------------------------------------------
// Anchor program client.
// ---------------------------------------------------------------------------

/**
 * Resolve the canonical Anchor program client. Pass an AnchorProvider made
 * from the user's Privy-embedded wallet (frontend) or the deployer keypair
 * (scripts). Reads the IDL bundled at web/src/lib/idl/kommit.json.
 */
export function getAnchorProgram(provider: anchor.AnchorProvider): anchor.Program<Kommit> {
  return new anchor.Program(idl as anchor.Idl, provider) as unknown as anchor.Program<Kommit>;
}

// ---------------------------------------------------------------------------
// Supabase clients.
// ---------------------------------------------------------------------------

/**
 * Browser-safe anon client. Reads only — RLS policies enforce.
 */
export function getSupabaseClient(): SupabaseClient {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !anonKey) {
    throw new Error(
      "NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY must be set"
    );
  }
  return createClient(url, anonKey);
}

/**
 * Server-only admin client. Bypasses RLS — never expose this key to the
 * browser. Used by the webhook handler to write into materialized state.
 */
export function getSupabaseAdminClient(): SupabaseClient {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceKey) {
    throw new Error(
      "NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set (server-side only)"
    );
  }
  if (typeof window !== "undefined") {
    throw new Error("getSupabaseAdminClient called in browser — service-role key must stay server-side");
  }
  return createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

// ---------------------------------------------------------------------------
// Live event subscription (client-side via Anchor's EventManager).
// ---------------------------------------------------------------------------

/**
 * Subscribe to a program-emitted event. Returns an unsubscribe function.
 * Use in client components to drive live UI updates without polling Supabase.
 *
 * Event names match the names emitted by programs/kommit/src/events.rs:
 *   'committed' | 'withdrawn' | 'projectCreated' | 'pointsAccrued'
 *   | 'supplyExecuted' | 'yieldHarvested' | 'projectMetadataUpdated'
 *
 * (Anchor TS converts snake_case event names to camelCase for the listener API.)
 */
export function subscribeToProgramEvents<T = unknown>(
  program: anchor.Program<Kommit>,
  eventName: string,
  handler: (event: T, slot: number, signature: string) => void
): () => Promise<void> {
  const listenerId = program.addEventListener(
    eventName as never,
    (event: unknown, slot: number, signature: string) => {
      handler(event as T, slot, signature);
    }
  );
  return () => program.removeEventListener(listenerId);
}

// ---------------------------------------------------------------------------
// Convenience: typed event payload shapes (matches programs/kommit/src/events.rs).
// ---------------------------------------------------------------------------

export type ProjectCreatedEvent = {
  project: PublicKey;
  recipientWallet: PublicKey;
};
export type CommittedEvent = {
  user: PublicKey;
  project: PublicKey;
  amount: anchor.BN;
  ts: anchor.BN;
};
export type WithdrawnEvent = {
  user: PublicKey;
  project: PublicKey;
  amount: anchor.BN;
};
export type PointsAccruedEvent = {
  user: PublicKey;
  project: PublicKey;
  activeDelta: anchor.BN;       // u128 → BN
  lifetimeTotal: anchor.BN;
};
export type SupplyExecutedEvent = {
  project: PublicKey;
  amount: anchor.BN;
  ts: anchor.BN;
};
export type YieldHarvestedEvent = {
  project: PublicKey;
  amount: anchor.BN;
  ts: anchor.BN;
};
export type ProjectMetadataUpdatedEvent = {
  project: PublicKey;
  newHash: number[]; // [u8; 32]
};
