/**
 * Lane B sandbox SPL mint — devnet-only, controlled by the visa-demo
 * fee-payer keypair. Distinct from Circle's USDC devnet faucet (which
 * rate-limits at $20 per few hours) so the judge surface can airdrop
 * unlimited test funds to first-time visitors.
 *
 * The mint pubkey is generated by `scripts/setup-sandbox-mint.mjs` and
 * persisted in `sandbox-mint.json` next to this file. The JSON ships
 * empty in the repo as a placeholder; the operator runs the setup
 * script once per environment, commits the result, and the constant
 * below resolves to a real pubkey at build time.
 *
 * Hard rule (per handoff 49 § Architecture context decision 3): the
 * token symbol never appears in UI strings. Internally we call it
 * "kUSD" in code comments and metadata, but rendered prices are
 * always `$X` (or `€X` where the existing surface uses EUR).
 */

import { PublicKey } from "@solana/web3.js";
import data from "./sandbox-mint.json";

export type SandboxMintInfo = {
  cluster: "devnet";
  decimals: number;
  /** Base58 mint pubkey, or "" before the operator has run setup. */
  mint: string;
  /** Base58 of the mint authority (= visa-demo fee-payer). */
  mintAuthority: string;
  createdAt: string | null;
};

const SANDBOX_MINT_INFO = data as SandboxMintInfo;

export const SANDBOX_MINT_DECIMALS = SANDBOX_MINT_INFO.decimals;

/** Throws if the operator hasn't run scripts/setup-sandbox-mint.mjs yet. */
export function getSandboxMint(): PublicKey {
  if (!SANDBOX_MINT_INFO.mint) {
    throw new Error(
      "Sandbox mint not initialized. Run `node scripts/setup-sandbox-mint.mjs` from web/ first.",
    );
  }
  return new PublicKey(SANDBOX_MINT_INFO.mint);
}

/** Same shape as `getSandboxMint` but returns null instead of throwing —
 *  for code paths (FE banners, status checks) that want to render a
 *  graceful unconfigured state. */
export function getSandboxMintOrNull(): PublicKey | null {
  if (!SANDBOX_MINT_INFO.mint) return null;
  try {
    return new PublicKey(SANDBOX_MINT_INFO.mint);
  } catch {
    return null;
  }
}

export function isSandboxMintConfigured(): boolean {
  return getSandboxMintOrNull() !== null;
}
